### ISSUE TITLE
Server Crash with Ticking Entity potioneffect

### ISSUE THREAD

**Issue by EmyLightsaber** [Darsenia/untouched_nature#3]
[crash-2023-02-27_18.03.02-server.txt](https://github.com/Darsenia/untouched_nature/files/10842742/crash-2023-02-27_18.03.02-server.txt)

Not really sure what's happening here. I was exploring a cave and the server suddenly crashed with a ticking entity.

**Comment by EmyLightsaber** [comment]
So, so far I've ruled out Universal Tweaks, by disabling it server-side.

**Comment by EmyLightsaber** [comment]
Looks like it's a problem between Apotheosis and Untouched Nature.

**Comment by Darsenia** [comment]
Did you use Antimagic potion while exploring the cave? 
The crash says that it's trying to apply Antimagic potion to a skeleton (or something like that) for some reason, that seems kinda... strange.
I still cannot test the modpack with MineFantasy and mixinBooter.If the issue is caused by them, I'm forceless.
Anyway, I'll check the potion code tomorrow.Maybe the potions should be protected from mobs, that want to use them =)
